version: "2"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-rails
    ports:
      - "3000:3000"
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/app
    links:
      - db
    environment:
      - DB_DEV=db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fernando
      POSTGRES_USER: fernando
      POSTGRES_PASSWORD: 1234

  box:
    build:
      context: .
      dockerfile: Dockerfile-debian

    working_dir: '/app'
    volumes:
      - .:/app