FROM ruby:2.4.1

RUN apt-get update
RUN apt-get install -y build-essential curl libpq-dev nodejs postgresql-client
RUN apt-get install -y git

WORKDIR /app
ADD . /app

RUN bundle install --jobs 9

EXPOSE 3000
EXPOSE 4242

RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*